### ISSUE TITLE
Multi-monitor support or at least dual monitor support

### ISSUE THREAD

**Issue by Jnss98b** [t1m0thyj/WinDynamicDesktop#117]
Can we get the ability to choose a different theme for each monitor?

**Comment by t1m0thyj** [comment]
As a dual monitor user I agree this would be nice. However the system API for setting wallpapers doesn't allow specifying which monitor to display them on. In order for this to work it would likely be necessary to have the program stitch images together across the monitors, which would be complex based on how many there are and if they have different resolutions. Because of the difficulty involved I don't plan to implement this feature.

**Comment by rocksdanister** [comment]
@t1m0thyj Its possible:
https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-idesktopwallpaper-setwallpaper

**Comment by t1m0thyj** [comment]
> @t1m0thyj Its possible:
> https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-idesktopwallpaper-setwallpaper
> ..although it will show the transition animation, is that a problem?

@rocksdanister I've tested that API and it won't show the fade transition. Were you able to enable the transition somehow?

**Comment by rocksdanister** [comment]
In my system with `Animate controls and elements inside windows` enabled, the fade transition is showing.

**Comment by x1han** [comment]
Regarding this issue, is it possible to change the wallpaper of only one monitor while keeping the wallpapers of the other monitors unchanged?
