### ISSUE TITLE
WDD 3.2.1: SmartScreen recognizes WinDynamicDesktop as a virus

### ISSUE THREAD

**Issue by FantasiaChan** [t1m0thyj/WinDynamicDesktop#122]
When version 3.2.1 was released, I immediately downloaded it. SmartScreen recognized it as a trojan, and did not let it run.

Windows 10, 3.2.1_Setup

**Comment by t1m0thyj** [comment]
The file does not contain any trojans and is clean according to VirusTotal: https://www.virustotal.com/#/url/580efa30c6df870de990735ce52782e755b852a038893577706eb932e84710aa/detection

The false positive is likely just because the file is very new, best thing that can be done is probably to report it as one.

**Comment by FantasiaChan** [comment]
I completely trust this app, but false positives are even stranger than true. Maybe it's the geolocation service.
