### ISSUE TITLE
Wallpaper Fitting Settings

### ISSUE THREAD

**Issue by MegaMarian12350** [t1m0thyj/WinDynamicDesktop#138]
On the latest version of the app, my custom theme (which is 16:9 ratio) fills over my 16:10 monitor, overwriting the 'fit" option in the Windows 10 Settings

Rather than fixing the problem, adding the wallpaper fitting settings (like the personalization page) would really apreciate most users.

Useful info:
- Windows 10 Pro 1903 (May 2019 Update) 64-Bit
- WinDynamicDesktop 3.3.0 (UWP / Microsoft Store Version)
- Theme: Custom (Windows Light colors theme - Different Brightness levels)

![Default Setting](https://user-images.githubusercontent.com/52240479/60191553-299b9580-983d-11e9-8f66-119686e23343.png)
![Expected Setting](https://user-images.githubusercontent.com/52240479/60191555-299b9580-983d-11e9-8b18-c423d9170f33.png)

**Comment by t1m0thyj** [comment]
Unfortunately due to limitations of Microsoft Store apps, the Store app only works with the Fill wallpaper setting. If you install the desktop version of the app instead, you can select the Fit setting in Windows 10 personalization options and the app should remember your choice. If switching to the desktop version doesn't resolve the issue, feel free to reopen this.
