### ISSUE TITLE
Pivot Possible?

### ISSUE THREAD

**Issue by m1keySAN** [t1m0thyj/WinDynamicDesktop#139]
Hi,

I love this SW, and have it installed on every computer which I have.
Could you integrate that if you use Pivot on the 2nd monitor, that it will get fullscreen?
Currently I looks like that
![Capture](https://user-images.githubusercontent.com/52319240/60339078-04776600-99a8-11e9-9b10-3e0f36488699.PNG)

**Comment by 18434351819** [comment]
Sorry ,I have one monitor only 

发送自 Windows 10 版邮件应用

发件人: Michael S.
发送时间: 2019年6月28日 19:24
收件人: t1m0thyj/WinDynamicDesktop
抄送: Subscribed
主题: [t1m0thyj/WinDynamicDesktop] Pivot Possible? (#139)

Hi,
I love this SW, and have it installed on every computer which I have.
Could you integrate that if you use Pivot on the 2nd monitor, that it will get fullscreen?
Currently I looks like that

**Comment by t1m0thyj** [comment]
@m1keySAN Are you using the Windows Store version of the app? Unfortunately due to limitations of what Store apps can do, that version of the app is unable to respect custom wallpaper fit settings.

If you try the desktop version instead, you should be able to select whatever wallpaper fit setting you want for your pivoted setup in Windows 10 Settings, and that should persist even after the wallpaper updates. If that doesn't work, feel free to reopen the issue.

**Comment by m1keySAN** [comment]
Nope, I use the portable .exe on a secure Windows 7 System.

And it doesn't fit.

**Comment by t1m0thyj** [comment]
On Windows 11, with one monitor landscape and the other one pivoted to be portrait, and the background fit set to "Fit", the image stretches without any empty space around it.
