### ISSUE TITLE
Port to a UWP?

### ISSUE THREAD

**Issue by moutasem1989** [t1m0thyj/WinDynamicDesktop#14]
I am just starting to learn C# so I am not by all means an expert,

I have been trying to port the code to a UWP app with a background task that periodically changes the Wallpaper and the lockscreen. so far I only got the location services and sunrisesunset API to work with a little success in applying the wallpaper which is fairly easy to do.
I couldn't do the scheduling part or registering the background task, unfortunately.
 The goal I am trying to get is to creat an interface in the app where pictures are chosen as ZIP file rather than downloading it through the app. The wallpaper of the desktop and/or the lockscreen change not only based on time of the day schedule but also based on weather.
(https://github.com/moutasem1989/ActiveDynamicWall)
I have tried setting the app to go through the images based on the time of the day but I still haven't managed to get it to work … any help is highly appreciated

**Comment by duble0** [comment]
Hi guys if you like, I can try to convert this project with Project Centennial(aka Desktop Bridge) and publish it in the Store, or if @t1m0thyj prefere publish by him self, can I give my support, let me know.

**Comment by t1m0thyj** [comment]
A lot of people have requested that I add this app to the Windows Store, so I am open to considering this. With Microsoft Imagine I believe I could register free as an app dev through my school.

It would also be nice to use the location API built into Windows, although this is completely unrelated to it being a Store app. I'd consider doing this too so people don't have to enter their location manually, but I don't want to require that this be turned on because personally I don't like giving Microsoft my location info at all times.

@moutasem1989 I'm afraid I can't really help with porting the code to a UWP app, since I'm not a C# expert either. I only learned the basics of it in college, and this is the first significant project I'm developing with it. I'm familiar enough with .NET to be able to use it, but don't know anything about UWP.

@duble0 Converting this project with Project Centennial is something I would be interested in, the main thing holding me back at this point is that Microsoft has a number of requirements before they will approve apps on the Windows Store, one of them being that [they must be tested to work on Windows 10 S](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-test-windows-s). I guess I could run Win10 S in a virtual machine and do that, but it seems like a lot of work.

**Comment by duble0** [comment]
@t1m0thyj  I already published apps converted with desktop bridge. Checks for Windows10 S aren't mandatory, I tested Asus Nova Go with some apps that are in the Store converted with Desktop Bridge. Some works well, other no. But I think that is a fluid situation that can change in the future, because in the next Windows releases could be used also the new .msix format that seem a game changer for app publishing.

Any way, if you are a .NET developers, you could easily create a UWP with your code using VisualStudio solutions for UWP, if you need there are many tutorials...

For the position question, IMHO, i think that you must make free the customer to choose if share location data or write it manually.

**Comment by casaout** [comment]
> With Microsoft Imagine I believe I could register free as an app dev through my school.
You don't need to be a student to get a free Microsoft developer account. And you can add a donate-button, so people could gift you with a beer for your great work!

**Comment by t1m0thyj** [comment]
Thanks all for your advice, it was helpful since I had no experience with developing Store apps. I researched it, and it seems like it should be quite simple to port the .NET app over using the Desktop Bridge in Visual Studio. I hope to get the app on the Windows Store sometime soon, will update this issue when/if I do.

**Comment by t1m0thyj** [comment]
I've done the work to port it and submitted it to the Windows Store, now awaiting Microsoft's certification before it will show up.

**Comment by casaout** [comment]
> I've done the work to port it and submitted it to the Windows Store, now awaiting Microsoft's certification before it will show up.

Fantastic news! I'd be interested to hear your experience in porting it using the desktop bridge. How much time did it take you and did you have to change a lot? Thanks for your awesome work!

**Comment by DragoCubed** [comment]
Going back to the donate button, it's apparently against the Store policy to have a donate button outside of the Store. Paint.net is paid on the Store because of said policy.

**Comment by t1m0thyj** [comment]
@DragoCubed Thanks for making me aware of this. I'm not sure if the Donate button the way I implemented it is a problem though. Paint.net had a Donate feature from inside the app, which is what I think Microsoft doesn't want inside their Store apps. Other open-source projects like Inkscape for example have free Windows Store apps, and still have a Donate button on their website. So I think having a Donate button on GitHub like I do should be fine, as long as I don't add it directly to the app.

**Comment by t1m0thyj** [comment]
@casaout Basically it took me two nights of work, but it wasn't really a terrible amount of work to do, I just didn't know what I was doing very well when I started out so there were some frustrations. I didn't have to change a ton, you can see in [this commit](https://github.com/t1m0thyj/WinDynamicDesktop/commit/706d44a2365818cf56158fec3de8191b7d1a4665) that a lot of new files were added, but most were automatically generated. The Desktop Bridge did most of the conversion pretty smoothly for me, after that the two biggest issues I had were (1) to figure out a way to structure the C# project so that I can build the desktop version in a way that supports Windows 7, while referencing UWP DLLs for the Store app version, and (2) to write a separate version of the code for the "Start on boot" option, since that works completely different between UWP and desktop apps (but I conveniently found most of the code I needed for that on a Microsoft dev's blog).

**Comment by casaout** [comment]
@DragoCubed uhh, I didn't know that. Interesting to forbid something like that. Then the PayPal donate button is probably the best solution :)

@t1m0thyj thanks for the clarifications! Yeah, the first steps with app stores can be frustrating (I've made my fair share of wasted hours in all three major app stores…), but I appreciate the opportunity to easily deploy/update apps for my users (and make sure they actually have the newest versions), get some simple statistics, and feedbacks/reviews…

**Comment by casaout** [comment]
> Provide the link to users and make them go download it and copy it to a certain folder. This may be the only option I really have, but I don't like how many extra steps it adds for setup.

Seems like that's the way to go, but it's also a bit suboptimal and cumbersome for many users. Did you, by any chance, find out what the license of Apple's pictures are? Another thing you could (maybe) do is to explain to people where they can download the zip-folder (and make it as easy as possible), but have a default set of very similar pictures. There are a number of free stock photo sites that you're allowed to use, e.g pexels.com or photl.com.

**Comment by t1m0thyj** [comment]
@casaout Thanks for the advice, I think I'm going to try option 1 first and see if it gets accepted. There are download manager apps on the Windows Store, so my assumption is that it's only file downloads not approved by the user that are prohibited. I wasn't able to find much information about the license of Apple's pictures other than [this on Stack Exchange](https://apple.stackexchange.com/questions/61410/what-is-the-license-on-mac-wallpapers).

**Comment by t1m0thyj** [comment]
It's been a week and I haven't forgotten about this issue, Microsoft took a while to get back to me. Unfortunately their download policy is more restrictive than I had hoped, so I definitely cannot have the UWP version of the app download images.

If I publish the app to the Windows Store, I don't want it to be cumbersome to set up, so I think the only options I am considering are to either package the images directly with the app, or to not publish a UWP version at all.

I've asked a question on [StackExchange](https://softwareengineering.stackexchange.com/questions/373540/potential-licensing-issues-with-bundling-apple-wallpaper-images) to hopefully get some legal advice. If bundling the images directly is not a feasible option, it would be unfortunate to not be able to publish the app, but IMO that's just the way it is because of Microsoft's restrictions.

**Comment by t1m0thyj** [comment]
It's been a week and I haven't forgotten about this issue, Microsoft took a while to get back to me. Unfortunately their download policy is more restrictive than I had hoped, so I definitely cannot have the UWP version of the app download images.

If I publish the app to the Windows Store, I don't want it to be cumbersome to set up, so I think the only options I am considering are to either package the images directly with the app, or to not publish a UWP version at all. Since bundling the images directly doesn't seem like a feasible option, unfortunately I don't think I can publish a UWP app right now because of Microsoft's restrictions.

**Comment by casaout** [comment]
Thanks for the update! I really think it'd be awesome if you find a way to publish it to the store, since this is something that especially non-technical people could love to use. 

But I agree with the comments on StackExchange - I wouldn't risk getting sued by Apple by using their photos (even though you have no commercial intensions). But you can use very similar photos (with a license you are allowed to use) and (almost) get the same job done. [pexels.com, photl.com, google pictures (tick: unrestricted license), etc.]

**Comment by t1m0thyj** [comment]
I was feeling pessimistic about this last night, but I would still like to release a Store app if possible, and I think I've thought of a good workaround. My plan is to publish a very simple webpage on GitHub, that will have the download link for the ZIP file. Then in the UWP version of the app, I will have a dialog with a link to this webpage for the user to open in their web browser. From this webpage, the ZIP file can be downloaded inside a browser instead of by the app. After the file is downloaded, the user can select the ZIP file from a file dialog in the app. While not as convenient as downloading automatically, I feel like it should be a simple process for non-technical users to follow if there are clear instructions provided.

@casaout Thanks for the encouragement, I appreciate it.

**Comment by casaout** [comment]
sounds good! Good luck! I am looking forward to download the app from the Store :)

**Comment by t1m0thyj** [comment]
The app has finally achieved certification and is now available on the Windows Store: https://www.microsoft.com/en-us/p/windynamicdesktop/9nm8n7dq3z5f

This version has not been tested a lot yet so there may be bugs. As always, if anyone has issues with the app, please report them.

**Comment by t1m0thyj** [comment]
Good news, Microsoft has said that "There was a mix-up by the Microsoft Store Team and any developer who was impacted by this can now resubmit their apps for publishing." I'm planning to submit an update to the  UWP app this weekend that enables automatic downloading of images like in the desktop app.

**Comment by casaout** [comment]
> The app has finally achieved certification and is now available on the Windows Store: 

Thanks again for your great effort on this! Awesome! And I like the store icon :)
