### ISSUE TITLE
New Theme: Firewatch Tower

### ISSUE THREAD

**Issue by rushelex** [t1m0thyj/WinDynamicDesktop#141]
FireWatch Theme with observation tower.

[FireWatch_Dynamic.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3360662/FireWatch_Dynamic.zip)

**Comment by 18434351819** [comment]
Ok ,think you,I will try it


发送自 Windows 10 版邮件应用

发件人: Алексей
发送时间: 2019年7月5日 7:50
收件人: t1m0thyj/WinDynamicDesktop
抄送: Subscribed
主题: [t1m0thyj/WinDynamicDesktop] New Theme: FireWatch (#141)

FireWatch Theme with observation tower.
FireWatch_Dynamic.zip
Submit your bug report or feature request here. If you have questions please ask them on Gitter instead.
When reporting a bug please provide:
• Steps to reproduce it
• Screenshots (if applicable)
• Log file (if it exists, see here for how to find it)
• Windows version (e.g. 7, 10)
• WinDynamicDesktop version (e.g. 2.0.0)
• Installation source (e.g. installer, Microsoft Store, portable EXE)

**Comment by FantasiaChan** [comment]
good theme

**Comment by rushelex** [comment]
> good theme

thank's 😊

**Comment by t1m0thyj** [comment]
@rushelex Thanks for submitting a new theme. Since there is already a [Firewatch theme for WDD](https://windd.info/themes/Firewatch.html), what would you say are the advantages of this version? Do you have a suggestion for what to name it to distinguish it from the already existing one?

One more thing, [a requirement](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes#managing-custom-themes) for theme submissions is:
> Also be sure to include a link for image credits so that proper attribution can be given.

Accordingly, please provide the link that these images were sourced from.

**Comment by rushelex** [comment]
The difference between this topic is that it depicts a fire tower.

The name has been changed to different.

[Firewatch_Tower.zip](https://github.com/t1m0thyj/WinDynamicDesktop/files/3772836/Firewatch_Tower.zip)

**Comment by t1m0thyj** [comment]
Thanks for the theme, uploaded to https://windd.info/themes :)
