### ISSUE TITLE
Automatically turn DarkMode not working

### ISSUE THREAD

**Issue by vladimirantos** [t1m0thyj/WinDynamicDesktop#142]
Hello,
I have a problem with automatically turn Dark mode. I don't know if this feature is supported. I found key `changeSystemTheme` in `settings.conf`. But when I set value true, after restart application, value is false again.
I installed application using Microsoft Store, version is 3.3.0 Windows version is 1903.

Thanks

**Comment by ondrej-mahdalik** [comment]
That's because MS Store apps are not allowed to change registry settings, which is, if I am correct, necessary in order to change theme settings.
Installing this app from GitHub instead of MS Store should fix this issue (works well for me).

**Comment by FantasiaChan** [comment]
why github version is always better?

**Comment by 18434351819** [comment]
Well, that's because the Windows store has jurisdiction over application permissions. Github compilation is the best choice.


------------------ 原始邮件 ------------------
发件人: "Ondřej Mahdalík"<notifications@github.com>;
发送时间: 2019年7月6日(星期六) 下午2:31
收件人: "t1m0thyj/WinDynamicDesktop"<WinDynamicDesktop@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [t1m0thyj/WinDynamicDesktop] Automatically turn DarkMode notworking (#142)




That's because MS Store apps are not allowed to change registry settings, which is, if I am correct, necessary in order to change theme settings.
 Installing this app from GitHub instead of MS Store should fix this issue (works well for me).

**Comment by t1m0thyj** [comment]
As others have already stated, this feature is unfortunately not possible in the Windows Store version, but is available if installed from GitHub.

**Comment by 18434351819** [comment]
Ok, thinks!
发送自 Windows 10 版邮件应用

发件人: Timothy Johnson
发送时间: 2019年9月24日 9:38
收件人: t1m0thyj/WinDynamicDesktop
抄送: hanxp; Comment
主题: Re: [t1m0thyj/WinDynamicDesktop] Automatically turn DarkMode notworking (#142)

As others have already stated, this feature is unfortunately not possible in the Windows Store version, but is available if installed from GitHub.
