### ISSUE TITLE
Avira detects WinDynamicDesktop as a trojan

### ISSUE THREAD

**Issue by DragoCubed** [t1m0thyj/WinDynamicDesktop#15]
Surely WinDynamicDesktop is safe, right? Should I mark it as safe?

**Comment by t1m0thyj** [comment]
Yes, this is a false positive, do not worry. Avira has been flagging it because the app is still new and has not been seen enough. According to [VirusTotal](https://www.virustotal.com/#/url/01dc858de6b107dc24fd239f9850b4f188c44d779142c4c4297a7a51e430a939/detection), none of the AV engines flag it as malicious.
