### ISSUE TITLE
Failed to build solution on Windows 10 x64 (Visual Studio 2019)

### ISSUE THREAD

**Issue by PetreBoboc** [t1m0thyj/WinDynamicDesktop#164]
![Capture](https://user-images.githubusercontent.com/19239394/65465876-13b26680-de66-11e9-8fc0-bdbbf3707c36.PNG)

I'm getting error CS0234: "The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)"

**Comment by t1m0thyj** [comment]
This error is likely caused by not having the correct version of the Windows 10 SDK installed. The `.csproj` file is looking for version 10.0.18362.0. If you do not have this version, either install it using the Visual Studio Installer, or modify the HintPath in the `.csproj` to point to a version of the SDK that you do have installed.

**Comment by PetreBoboc** [comment]
Thank you!

What I had to do was to change from ` <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Runtime.WindowsRuntime.dll</HintPath> ` to  `<HintPath> D:\Windows  Kits\10\UnionMetadata\10.0.18362.0\Windows.winmd </HintPath>` inside file `WinDynamicDesktop.csproj` because Visual Studio is installed on `D:\` partition, in my case.
