### ISSUE TITLE
What happend with Night Mode feature? Why it replaced by Night wallpaper only mode?

### ISSUE THREAD

**Issue by disablesilence** [t1m0thyj/WinDynamicDesktop#172]

**Comment by t1m0thyj** [comment]
This feature was called "Dark Mode" in previous versions of the app. The name was changed to make it clear that the only thing it does is to show night time wallpapers all the time, and never shows daytime ones.

Previously selecting this setting also changed your Windows theme to be dark. That behavior was removed because it seemed unnecessary, you can easily change the Windows theme yourself if you want. When dark mode is not enabled, the option is still supported to automatically change your Windows theme, so no functionality has been lost.

**Comment by disablesilence** [comment]
Oh, ok. I used this option sometimes when I needed to temporarily switch to dark mode.
It's not a big problem. I will make a shortcut to the Windows setting.
