### ISSUE TITLE
Dark mode at night?

### ISSUE THREAD

**Issue by alfredchickens** [t1m0thyj/WinDynamicDesktop#178]
Even though there are separate programs/scripts for doing so, adding a "dark mode at night" feature would be a great integration.

I love the software!

**Comment by t1m0thyj** [comment]
By "dark mode at night", I'm assuming you mean to change the Windows 10 theme between light during daytime and dark at night. This feature is already present in the app, but only in the version available on GitHub. Unfortunately, the Microsoft Store version is unable to support it due to technical limitations.
![image](https://user-images.githubusercontent.com/22344007/69598853-c921a780-0fd8-11ea-84ff-4c6a1070bdc2.png)
