### ISSUE TITLE
Avast detection

### ISSUE THREAD

**Issue by MrAlexEsisteGia** [t1m0thyj/WinDynamicDesktop#18]
Avast's avg module is triggered when you click "start on boot", the module is idp.alexa.51

**Comment by DanielVafidis** [comment]
Avira also

**Comment by t1m0thyj** [comment]
This is a false positive, do not worry. The app is still new and some AV software is flagging it because has not been seen in the wild enough yet. According to [VirusTotal](https://www.virustotal.com/#/url/01dc858de6b107dc24fd239f9850b4f188c44d779142c4c4297a7a51e430a939/detection), none of the AV engines flag it as malicious.

**Comment by t1m0thyj** [comment]
Closed as duplicate of #15. Unfortunately I don't think I can really do much about this, if you're using AVG or Avira please submit them to be reviewed as false positives.
