### ISSUE TITLE
Multi-monitor / "Across multiple screens" support

### ISSUE THREAD

**Issue by jmxd** [t1m0thyj/WinDynamicDesktop#187]
Right now it shows the wallpapers completely on each individual screen instead of the option to show one wallpaper across all screens. It's possible to go to the settings and manually enable the option, but with each change to a new wallpaper it gets reset back to "fill" option

**Comment by aserraric** [comment]
I just thought to myself "How hard could it be?". Turns out, it's impossible with the app as it is.

Apparently, there is no API for UWP (Microsoft Store) apps, it would require a write to the registry (HKEY_CURRENT_USER\Control Panel\Desktop\WallpaperStyle must be set to 22). But UWP apps are not allowed to modify the registry.

**Comment by TroyB9** [comment]
> I just thought to myself "How hard could it be?". Turns out, it's impossible with the app as it is.
> 
> Apparently, there is no API for UWP (Microsoft Store) apps, it would require a write to the registry (HKEY_CURRENT_USER\Control Panel\Desktop\WallpaperStyle must be set to 22). But UWP apps are not allowed to modify the registry.

Except that the source code looks like it is already using a registry tweaker powershell to accomplish some registry tasks.   It would be nice to see this feature along with the usual settings of fill, fit, stretch, tile, center, span.   In addition a collection of wallpapers that are naturally in wide aspect ration which lends itself to landscapes in general.

**Comment by aserraric** [comment]
Alright, never mind me. Apparently the UWP app is just a wrapper for a regular Win32/.NET executable. So registry access is possible. Then why does the program even use the (severely limited) UWP API?

**Comment by t1m0thyj** [comment]
This is a known issue in the Microsoft Store app (see [the wiki](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Known-issues#wallpaper-fit-not-saved-with-multiple-monitors)). It can be worked around by either resetting the app after changing wallpaper fit in the Windows 10 settings, or switching to the desktop version of the app.

> But UWP apps are not allowed to modify the registry.

This is correct. Even though the UWP app is just a wrapper around a regular executable, that is still the case.

> Except that the source code looks like it is already using a registry tweaker powershell to accomplish some registry tasks.

Powershell scripts that perform registry tweaks will only work in the desktop version, in the Microsoft Store app they are still not allowed to modify the registry because they run inside the app.

> Then why does the program even use the (severely limited) UWP API?

The Active Desktop API used by the desktop app would be more ideal, but due to UWP limitations it is unable to update the WallpaperImage path in the registry. Therefore, on startup, the wallpaper background will be totally black for a moment until WinDynamicDesktop launches. The UWP API, although limited, is the only method I have found that can bypass the registry limitations.

**Comment by t1m0thyj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #187: Multi-monitor / "Across multiple screens" support](https://trello.com/c/0WfrUKl8/128-issue-187-multi-monitor-across-multiple-screens-support)
