### ISSUE TITLE
Scripts not working - Default Execution Policy restricted

### ISSUE THREAD

**Issue by OEssHRERLr770rGGLOH0** [t1m0thyj/WinDynamicDesktop#192]
I've installed 2 of the scripts you wrote (ChangeWindowsSystemTheme.ps1 and ChangeWindowsAppTheme.ps1) and they don't do anything. 

However, I've tested SampleScript.ps1 and when I click the refresh wallpaper button, the params appear in a message box. So scripts are getting executed.

I think the problem is that ~~script execution is disabled on my system~~ the Default Execution Policy is set to restricted so scripts executed by WDD are aborted before they can change the registry keys.

I extracted the part of your script that changes the registry and when I tried to manually run it, I had to use the arguments suggested [here ](https://superuser.com/a/533745) or it wouldn't work:

`powershell.exe -noprofile -executionpolicy bypass -file .\script.ps1
`

Is there any way to bake that into WDD? Or am I missing something and scripts should be working out of the box? Thanks!

 - Windows 10
 - WinDynamicDesktop Version 4.0.0 (UWP)
 - Installation source: Microsoft Store

**Comment by PaoloC95** [comment]
Also the script "ChangeLockScreenImage.ps1" not change che lockscreen image when is checked the option to blur the wallpaper; if isn't checked it work.
- Windows 10 (1909)
- WinDynamicDesktop 4.0.0
- Installation from GitHub (setup)

**Comment by ArchFeh** [comment]
Change Display Brightness         work fine
Change Windows App Theme    doesn‘t work
Change Windows System Theme    doesn't work

- Windows 10 (1909)
- WinDynamicDesktop Version 4.0.0(UWP)
- Installation source: Microsoft Store

**Comment by t1m0thyj** [comment]
The limitations of the scripts mentioned are documented here: https://windd.info/scripts/

The scripts for changing Windows 10 app/system theme are marked "Desktop Only", and the script `ChangeLockScreenImage.ps1` is "Experimental" because it doesn't work consistently.

If you have issues with the scripts, feel free to report them in this repo: https://github.com/t1m0thyj/WDD-scripts

WDD adds this line before any PowerShell script that it runs:
`Set-ExecutionPolicy Bypass -Scope Process -Force`
so the problem isn't the execution policy.

The reason why some scripts won't work is that Microsoft Store apps aren't allowed to modify the registry, even inside PowerShell scripts invoked by the app. The scripts for changing Windows 10 app/system theme require changing a registry key. I tried to work around this by calling a separate process `reg.exe` in the PowerShell scripts, which bypassed the registry limitation. However, this occasionally popped up a Command Prompt window, it would flash on the screen even when I passed a command line flag to hide it, which isn't acceptable behavior for WDD.
