### ISSUE TITLE
Wallpaper ordering incorrect

### ISSUE THREAD

**Issue by code4t2** [t1m0thyj/WinDynamicDesktop#195]
Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide: 
 - Steps to reproduce
 | 1. Run the application
 - Log file (unnecessary)
 - Windows version (10 - 1909)
 - WinDynamicDesktop version (e.g. 4.0.0 - UWP)
 - Installation source (e.g. installer, Microsoft Store)

Reference: 
Please see the image for accurate ordering from dawn to midnight:
Row 1 - Dawn to sunrise
Row 2 - Morning to noon
Row 3 - Afternoon to sunset
Row 4 - Dusk to midnight  
![image](https://user-images.githubusercontent.com/12026677/77851294-f46e0a80-71f5-11ea-951e-d29d53a622f0.png)
Note that the lighting lightens from the right side of the dune in the morning and the left side is lit afternoon. The two evenly lit images represent noon and midnight. 
  
Actual issue:
The image for dawn is shown at dusk. 

Apologies if it seems like nitpicking, but attention to detail is, what I believe, makes for such an incredible UX by 🍎

**Comment by t1m0thyj** [comment]
> The image for dawn is shown at dusk.

To be more specific, is the issue that images 10 and 11 are switched in WDD? That seems to be what I'm seeing when I compare your thumbnails against the bundled Mojave theme.

**Comment by code4t2** [comment]
No, I reordered these images from an image dump in what I perceived as the correct order based on the lighting and fading. The order is different in the application. I currently do not have access to the computer that I installed your application on. I shall post updates when I do, sooner if you could tell me where to find the data on my computer.

**Comment by code4t2** [comment]
Was able to look at this again, so the image numbered 0 appears in the evening on my computer when it should be pre-dawn. 

![image](https://user-images.githubusercontent.com/12026677/80732562-2262a980-8b2a-11ea-88fc-e4c52b390683.png)
(notice the time)

**Comment by t1m0thyj** [comment]
@code4t2 I extracted the solar metadata from Apple's Mojave Desert HEIC:
```json
[
  {
    "ap": {
      "l": 0,
      "d": 15
    },
    "si": [
      {
        "a": -0.34293897337389534,
        "z": 270.9335726142445,
        "i": 0
      },
      {
        "a": -10.239533359185998,
        "z": 81.7760622301883,
        "i": 1
      },
      {
        "a": -4.24750738479075,
        "z": 86.33562024653418,
        "i": 2
      },
      {
        "a": 1.3892919153460956,
        "z": 90.81283900641841,
        "i": 3
      },
      {
        "a": 7.1673918960737275,
        "z": 95.30758065752053,
        "i": 4
      },
      {
        "a": 13.086416721109808,
        "z": 99.92080704167716,
        "i": 5
      },
      {
        "a": 40.415814935346006,
        "z": 129.18681159417304,
        "i": 6
      },
      {
        "a": 53.433464184021446,
        "z": 182.23356561823599,
        "i": 7
      },
      {
        "a": 38.79294767322197,
        "z": 233.55186665297836,
        "i": 8
      },
      {
        "a": 11.08920282367486,
        "z": 261.87176360765403,
        "i": 9
      },
      {
        "a": 5.184357137920458,
        "z": 266.44344179949627,
        "i": 10
      },
      {
        "a": -6.248532117899824,
        "z": 275.4422146409933,
        "i": 11
      },
      {
        "a": -12.207927518408935,
        "z": 280.07049146493375,
        "i": 12
      },
      {
        "a": -39.4895116503885,
        "z": 309.4188591343152,
        "i": 13
      },
      {
        "a": -52.753172382225095,
        "z": 2.1755754989210345,
        "i": 14
      },
      {
        "a": -38.04725026362508,
        "z": 53.50936411505717,
        "i": 15
      }
    ]
  }
]
```

Where "a" represents altitude, "z" represents azimuth, and "i" represents image index. The azimuth (angle of the sun) is 90° when it rises in the east, and 270° when it sets in the west. Based on this, I assume the sun's angle is approximately 0° at midnight and 180° at noon.

To order the images throughout a 24-hour cycle, I sorted the image indices in the metadata according to ascending order of azimuth:
`14, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 11, 12, 13`

The image indices used by WDD are 1 greater than the image indices used by Apple (because they are 1-indexed rather than 0-indexed). Converting the Apple indices to WDD indices, I get:
`15, 16, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 12, 13, 14`

This is exactly the same order found in the Mojave Desert `theme.json` for WDD:
```json
{
  "imageFilename": "Mojave_Desert_*.jpg",
  "imageCredits": "Apple",
  "sunriseImageList": [2, 3, 4],
  "dayImageList": [5, 6, 7, 8, 9, 10, 11],
  "sunsetImageList": [1, 12, 13],
  "nightImageList": [14, 15, 16]
}
```

The sequence begins with index 15 in the middle of the night (midnight), and ends with index 14.

I believe this proves that the image order in WDD is correct, since it is identical to the order used by Apple's dynamic Mojave wallpaper.

**Comment by code4t2** [comment]
Thanks for taking a deep look into this, Timothy. The issue I raised was based on visual inspection of the light tones and shadows only. The conclusion being either my analysis was incorrect or the HEIC data might be, due to retouching etc.
