### ISSUE TITLE
Import theme window will not load

### ISSUE THREAD

**Issue by dctreu** [t1m0thyj/WinDynamicDesktop#205]
Hi!

I am trying to create a custom theme, but the "Importing theme" window stays at 0% without moving. Below is a screenshot of the .ddw file (on the left) and the code of the theme.json file inside (on the right)

![image](https://user-images.githubusercontent.com/61584712/82438590-9a711f00-9a99-11ea-931d-524e5618b731.png)

I am running the latest version of WinDynamicDesktop on Windows 10.

Thanks!

**Comment by t1m0thyj** [comment]
The contents of `theme.json` aren't valid JSON, each line except for the last one needs to have a comma after it. You can paste the file in [this online editor](https://www.jsonschemavalidator.net/) to check it for syntax issues.

You've also discovered a bug 😄 The theme importer process should show an "invalid JSON" message in this case, rather than hanging at 0%.

**Comment by dctreu** [comment]
Thank you! It is indeed working now, with valid syntax. Glas to know I accidentally discovered a bug in my bug report though.
Thanks a lot for your work on this, I really appreciate it!

**Comment by t1m0thyj** [comment]
The issue with the import process hanging was fixed in f0088f4. The fix will be in the next version.
