### ISSUE TITLE
errors suddenly trying to launch on startup and normally

### ISSUE THREAD

**Issue by TheGoldmasterCorporation** [t1m0thyj/WinDynamicDesktop#209]
had this issue before, but if I try to launch win dynamic I get this problem. it works fine until it runs into this issue. the only temporary fix is to reset the app. I think it was because of trying to use a custom theme like Seoul 24 hour theme (https://mega.nz/file/Jx5hHB7K#dZCqivcprmyftL2hORhXBtAuisBnYy0QYTl1xopq4DY) and I haven't done something right in the JSON file. I converted from http://dynwalls.com/

[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/4680373/WinDynamicDesktop.exe.log)

![Capture](https://user-images.githubusercontent.com/7105970/82869491-43020180-9f26-11ea-8b32-652792662a65.PNG)

**Comment by t1m0thyj** [comment]
Your theme JSON file is missing a closing brace. To ensure that it is valid JSON, you can use [JSONLint](https://jsonlint.com/).

Fixing the JSON should make the error disappear for now. The next version of WDD will have better error handling to provide more details about the error when there is invalid JSON, instead of unexpectedly throwing an error.
