### ISSUE TITLE
Avira detects WinDynamicDesktop as a trojan

### ISSUE THREAD

**Issue by DragoCubed** [t1m0thyj/WinDynamicDesktop#21]
Is this a false positive? Surely WinDynamicDesktop is safe. Could someone help me out? I don't know whether to unblock it or not.

**Comment by t1m0thyj** [comment]
Yes, this is a false positive, do not worry. Avira and AVG have been flagging it because the app is still new and has not been seen enough. According to the 68 engines on [VirusTotal](https://www.virustotal.com/#/url/a592f7a716ba1487a41377fe822d240df104612c119ec616dab5c8a519aaad97/detection), the file is not malicious. If you are able, please submit the EXE to be reviewed as a false positive.

**Comment by DragoCubed** [comment]
I just filed a false positive. Hopefully Avira unflags it. Speaking of VirusTotal, I ran the .exe through it and 
 CrowdStrike Falcon detected the file. https://www.virustotal.com/#/file/6215fa78878d6d72f92793b84ae12c001dbad212fb0e29f0bfa3b161235e2ad9/detection

**Comment by skyel1u** [comment]
Maybe @t1m0thyj can support SHA-256 or SHA-1 on the download page, we can check the sum that before we install it.

**Comment by t1m0thyj** [comment]
@DragoCubed I've been keeping this issue open so that people are aware of it, although I can't really do anything to fix it. Is Avira still flagging the latest version? If so, I'll keep the issue open until AV programs detecting the app as false positive.

@skyel1u That's not a bad idea, I'll consider doing that for the next release.

**Comment by t1m0thyj** [comment]
Version 1.3 has just been released, here are the SHA-256 hashes:
226d0a518a9d06a481ef2ae10a4b61ff621f1e7325339e246ba91f4e848688d2 *WinDynamicDesktop.exe
b8cc99c86c377300c7b148d8f0a14451041f8935c06f7efaf7e5f4f776984e91 *WinDynamicDesktop_1.3_Setup.exe
