### ISSUE TITLE
PowerShell scripts not working with Microsoft Store Verison

### ISSUE THREAD

**Issue by chenzhe82807544** [t1m0thyj/WinDynamicDesktop#213]
Seems PowerShell scripts not working with Microsoft Store Verison.
Enabled PowerShell scripts and click "Refresh Wallpaper", then nothing happened. No error window pop-up or any event log to windows log, the valve in the registry did not change.
Once I remove WinDynamicDesktop and reinstall with the .exe setup file, this function work as designed.

 - Windows version: Windows 10 1909
 - WinDynamicDesktop version: 4.1.1
 - Installation source: Microsoft Store

**Comment by t1m0thyj** [comment]
Several of the PowerShell scripts listed [here](https://windd.info/scripts) are labelled "Desktop Only":
![image](https://user-images.githubusercontent.com/22344007/85902203-7b208c80-b7d1-11ea-92b0-05035c7dab60.png)
This is because they require permissions that are not granted to Microsoft Store apps.

**Comment by chenzhe82807544** [comment]
> Several of the PowerShell scripts listed [here](https://windd.info/scripts) are labelled "Desktop Only":
> ![image](https://user-images.githubusercontent.com/22344007/85902203-7b208c80-b7d1-11ea-92b0-05035c7dab60.png)
> This is because they require permissions that are not granted to Microsoft Store apps.

My bad, didn't see that label😋
