### ISSUE TITLE
Png files

### ISSUE THREAD

**Issue by Cyberorzechowy** [t1m0thyj/WinDynamicDesktop#224]
Is it possible to support png files because jpg has worse quality?

**Comment by t1m0thyj** [comment]
WinDynamicDesktop does support PNG files if you want to use them in your own theme. The macOS themes bundled with WDD are in JPEG format, because PNG would make the downloads too big.

The quality of the JPEG images is 98%, the highest percentage I believe is worthwhile without diminishing returns. (The difference between 98% and 100% is very small in terms of visible quality and very large in terms of file size.)

If you want the macOS themes in lossless PNG format, I've created a [Multi-Image HEIC Extractor](https://windd.info/heic/) which can be used for this.
