### ISSUE TITLE
[Feature Request] Add the ability to start a program at logon

### ISSUE THREAD

**Issue by rushelex** [t1m0thyj/WinDynamicDesktop#232]
Add the ability to start a program at logon so that the program starts faster and does not wait for other programs to start at startup.

**Comment by ddasutein** [comment]
Not sure if this is even related to WinDynamicDesktop. You can already set this app to run at startup in the options menu? Or if you are asking for a feature to let WinDynamicDesktop open other apps at startup, this is redundant as you can use the `Startup` folder. This can be accessed by `CTRL + R` and typing in the Run dialog `shell:startup` then add a shortcut to an app that you want to launch at startup.

Aside from that, you really don't have control on when applications get priority on when they can start. If you haven't already gotten an SSD for your computer, you might as well get one.

**Comment by t1m0thyj** [comment]
@rushelex Windows apps don't have the ability to request to be started with high priority immediately at logon. They can only be added to a list of programs to run on startup, whose order cannot be controlled as @ddasutein mentioned.

That being said, there may be a few ways to make WDD start faster:
* Follow [this guide](https://www.howtogeek.com/403162/how-to-disable-the-windows-10-startup-delay/) to remove default startup delay of 10 seconds before programs load at startup. This may make WDD start earlier, but does not solve it waiting for other programs to start.
* Follow [this guide](https://www.sevenforums.com/tutorials/67503-task-create-run-program-startup-log.html) to create a scheduled task that runs WDD at log on (instead of at startup). I haven't tested starting WDD in this way, so can't guarantee that it will work.

**Comment by t1m0thyj** [comment]
Reply from @rushelex:
> Hey. Despite the fact that I respect you, you are wrong.
> Check out this app: https://github.com/Armin2208/Windows-Auto-Night-Mode. It has the option to start not from the Startup folder, but from the Windows Task Scheduler. If the program is launched from the Windows Task Scheduler, the program starts immediately when the computer is turned on and does not wait for other programs to start.
> I tried to add the launch of the program myself as a scheduled task, but I could not find where the .exe file of the program itself is located. I am using the UWP version of the program.
> 
> P.S. My PC has an SSD and the 10 second delay before starting programs is disabled for me.

**Comment by t1m0thyj** [comment]
@rushelex The .exe file for WDD can be found by following these steps: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed

This could get messy to implement for reasons described [here](https://github.com/TranslucentTB/TranslucentTB/issues/135). Another workaround besides Task Scheduler is [EarlyStart](https://github.com/sylveon/EarlyStart).

**Comment by emberaholdon** [comment]
> @rushelex The .exe file for WDD can be found by following these steps: https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed
> 
> This could get messy to implement for reasons described [here](https://github.com/TranslucentTB/TranslucentTB/issues/135). Another workaround besides Task Scheduler is [EarlyStart](https://github.com/sylveon/EarlyStart).

Use task scheduler to start the app at logon. Faster than autostart items.

**Comment by t1m0thyj** [comment]
I don't plan to implement this feature directly in WDD for reasons mentioned above. However to make it more convenient to set up the scheduled task to run at logon, I've created PowerShell scripts to automate this: https://github.com/t1m0thyj/WDD-scripts/tree/master/standalone#installuninstall-startup-task
