### ISSUE TITLE
Question: What are the differences between distributions? 

### ISSUE THREAD

**Issue by Geeyun-JY3** [t1m0thyj/WinDynamicDesktop#242]
What are the differences between installer(`.exe`), portable and Store versions?

Suggestion: set up a `Question` issue template.

**Comment by t1m0thyj** [comment]
The differences are minimal, mostly just different methods of installing the app:
* Portable - Single file executable (only the WDD program)
* Installer (.exe) - Installer that contains "portable" distribution, but also has ability to create start menu/desktop shortcuts, make WDD launch at boot, and associate .ddw files in File Explorer
* Store - WDD packaged for the Microsoft Store (similar to the installer since it creates start menu shortcuts, makes WDD launch at boot, and associates .ddw files)
* Chocolatey package - Downloads the installer and runs it in silent mode

One additional difference of the Store app is that it uses a UWP (Universal Window Platform) API to change wallpaper images, unlike other versions of the app that use the Windows Shell API (which is subject to limitations when called by a Store app).

Feel free to open "Question" issues without a template, or ask questions on Gitter.

**Comment by Geeyun-JY3** [comment]
thx :-)
