### ISSUE TITLE
Wallpaper not refreshing automatically, have to use manual option

### ISSUE THREAD

**Issue by jaKz9** [t1m0thyj/WinDynamicDesktop#25]
I'm using the latest portable version, Start on Boot enabled, location Europe, and the wallpapers aren't updating automatically. I always check with the "manual refresh" option to see if it's working and most of the time the program is stuck to an earlier hour. Is this an issue of mine or is there a bug within the program? Not implying anything, I love the concept, just wish it would be auto.

**Comment by spike1234** [comment]
I have the same configuration and the same problem.

**Comment by MYRLOYY** [comment]
v 1.2.1 same problem

**Comment by MYRLOYY** [comment]
At OS loading the wallpaper is put correct, but then it does not change automatically

**Comment by jaKz9** [comment]
@MYRLOYY Exactly! When I log on the wallpaper is correctly adjusted, but it's stuck afterwards.

**Comment by DogBrown** [comment]
ME TOO,Windows 1803

**Comment by Skyr3n** [comment]
Same problem too

**Comment by DragoCubed** [comment]
I have the same issue. Windows 10 1803, installer.

**Comment by t1m0thyj** [comment]
Just released an update (v.1.2.2) that should hopefully fix this. Was a very weird error to debug, somehow changing to using a different C# Timer class fixed it (although .NET Framework has 4 different timer classes, which is confusing). Not sure if the current fix is ideal, but at least it worked when I tested it.

**Comment by t1m0thyj** [comment]
For my own future reference:
I understand why changing the timer fixed things now. The code to change the wallpaper doesn't work unless you run it in the main thread, which is what System.Windows.Forms.Timer does (because its part of the GUI library, it runs tasks in the main GUI thread). The one I was using previously (System.Timers.Timer) tried to set the wallpaper in a separate thread.
