### ISSUE TITLE
Select Specific Image from Pack as Wallpaper

### ISSUE THREAD

**Issue by JSR-FR** [t1m0thyj/WinDynamicDesktop#256]
Hi all,
The issue is when we buy a wallpaper pack with multiple images inside, we don't always like all of them.
It would be great to be able to pick which one to display at the moment and not be forced to see the one fixed  for the hour in the pack.
Could you guys add this feature ?
That would be top.
Thank you very much

**Comment by t1m0thyj** [comment]
WDD is designed to show all images from a theme, since dynamic desktop wallpapers are created with an ideal number of images to be shown throughout the day.

If you don't like certain images in a theme, feel free to copy an existing theme and update its JSON file to remove certain images (see https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Creating-custom-themes for how theme.json files are structured).
