### ISSUE TITLE
Automatic change lock screen

### ISSUE THREAD

**Issue by zhaojinpeng111** [t1m0thyj/WinDynamicDesktop#31]
Change lock screen picture same as desktop

**Comment by t1m0thyj** [comment]
I like this idea, from a standpoint of trying to imitate Mojave's Dynamic Desktop feature this makes sense because the lockscreen image on macOS is the same as the desktop wallpaper as far as I can tell.

However, it doesn't seem like there's a good API to change the Windows lockscreen image in C#. Also in order for it to look good the image would have to update before the lockscreen image loads on the screen, and I'm not sure I would be able to do that.

The real solution to this problem would be to somehow make Windows use the desktop wallpaper as the lockscreen image. I wish this feature was built-in to Windows, and unfortunately I'm not aware of any program that does this, probably because of the reasons I mentioned above.

**Comment by okms** [comment]
Hi, 

First of all: thank you for putting so much time and effort into developing this great app. Really. It's awesome. 

I know this issue is closed but just wanted to ask you @t1m0thyj if setting the lockscreen in the UWP app could be possible using something like this: https://docs.microsoft.com/en-us/uwp/api/windows.system.userprofile.userprofilepersonalizationsettings

**Comment by t1m0thyj** [comment]
I've tried using the UWP API in WDD with the [experimental `changeLockscreen` setting](https://github.com/t1m0thyj/WinDynamicDesktop#can-the-lockscreen-image-be-changed-too). Unfortunately it doesn't work, the image changes only once and stays the same afterwards, even when the API is called repeatedly with different images. This is an issue [that was reported 4 years ago](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c5f7e014-a1a1-4d62-b550-7976381d62cd/change-windows-8-lockscreen-image-with-wpfservice-only-works-once?forum=wpf), but has yet to be acknowledged or fixed by Microsoft.

**Comment by abdullah20401** [comment]
@t1m0thyj So I was looking through the scripts on [windd.info](https://windd.info/scripts/), and I saw that you had Change Lockscreen Image as an experimental script. So does it work ?
![Screenshot 2020-08-06 at 11 28 33 AM](https://user-images.githubusercontent.com/44303300/89557263-29a7ec00-d7d8-11ea-9808-249266c85818.png)

**Comment by Darthagnon** [comment]
[Winaero Lock Screen Customizer for Windows 8 and 8.1](https://winaero.com/lock-screen-customizer-for-windows-8-1-and-windows-8/) can change the lockscreen image, as can [Windows 7 Lockscreen Changer](https://sourceforge.net/projects/windows7lockscreenchanger/) and the classic [Julien Manici's Windows 7 Logon Background Changer](http://www.julien-manici.com/windows_7_logon_background_changer/) - might be some implementation ideas in those programs?

**Comment by myfix16** [comment]
I wrote a WPF application with the LockScreen class:
```
using System;
using Windows.Storage;
using Windows.System.UserProfile;

    public class ImageChanger
    {
        public static async Task ChangeLockScreenImage(string path)
        {
            var file = await StorageFile.GetFileFromPathAsync(path);
            await LockScreen.SetImageFileAsync(file);
        }
    }
``` 
And call it in App.xaml.cs:
```
public partial class App : Application
    {
        public App()
        {
            var path = Environment.GetCommandLineArgs()[1];
            Task.Run(async () =>
            {
                await ImageChanger.ChangeLockScreenImage(path);
                Environment.Exit(0);
            });
        }
    }
```
Then I run the app with a powershell script using WDD's powershell script functionality:
```
param (
    [Parameter(Mandatory=$true)][int]$daySegment2,  # 0 = Day, 1 = Night
    [Parameter(Mandatory=$true)][int]$daySegment4,  # 0 = Sunrise, 1 = Day, 2 = Sunset, 3 = Night
    [Parameter(Mandatory=$true)][string]$imagePath  # Path to current wallpaper image
)

<Some Path>\LockScreenSync.exe $imagePath
```

And it works fine for me. Maybe calling this API with a temporary process can make it work.
