### ISSUE TITLE
dark mode system based

### ISSUE THREAD

**Issue by techgue** [t1m0thyj/WinDynamicDesktop#316]
i'd like to see the wallpaper changing automatically with the system

**Comment by t1m0thyj** [comment]
Could you describe in more detail what you mean? Do you want an "automatic night mode" that will be enabled when Win10 dark mode is turned on, instead of the manual Night Mode setting in WDD?
![image](https://user-images.githubusercontent.com/22344007/120086800-155b1580-c0b0-11eb-82f3-01cf1c6de3b4.png)

**Comment by techgue** [comment]
yep

**Comment by Geeyun-JY3** [comment]
Try the [PowerShell scripts](https://github.com/t1m0thyj/WDD-scripts).

**Comment by t1m0thyj** [comment]
@techgue Do the PowerShell scripts for changing Windows app theme and system theme implement the behavior you want?
