### ISSUE TITLE
Application bar don't change theme

### ISSUE THREAD

**Issue by PaoloC95** [t1m0thyj/WinDynamicDesktop#337]
Hi,
i've updated my windows to beta channel and the script for change system theme (https://raw.githubusercontent.com/t1m0thyj/WDD-scripts/master/stable/ChangeWindowsSystemTheme.ps1) doesen't work.
On the explorer and the system apps that's all done.
Scripts are enabled and i've replaced the script downloading again from link above.

- WDD Version: 4.6.0
- OS Version: Windows 10 Home 21H1 (Build 19043.1052 - Windows Feature Experience Pack 120.2212.3740.0)

Steps to Reproduce:

1. Wait until the night and the theme of application bar doesen't change.

Are you using the Microsoft Store version of WDD?: No, downloaded from github (installer)

![image](https://user-images.githubusercontent.com/43925971/121800037-da202100-cc2f-11eb-828e-fe240f974ce0.png)

**Comment by t1m0thyj** [comment]
What happens if you go to `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize` in the Registry Editor and toggle the value of "SystemUsesLightTheme"? This is what the PowerShell script does behind the scenes.
![image](https://user-images.githubusercontent.com/22344007/122300682-a06c4600-cecd-11eb-9492-fd5d86f6feca.png)

**Comment by robbely** [comment]
I'm getting the same issue after updating to WDD v4.6 (I haven't tried 4.7) from 4.4.
Reverting to 4.4 fixes it, so it looks like a bug introduced between 4.4 and 4.6

**Comment by t1m0thyj** [comment]
This should be fixed in WDD 5, although there is now a separate issue where the theme changes only partially (#463)
