### ISSUE TITLE
Old Version on Widget

### ISSUE THREAD

**Issue by iMonZ** [t1m0thyj/WinDynamicDesktop#404]
Hey,

I wondered why my installed version of this tool is so old.
Could  you please update the version on Winget?
https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/t1m0thyj/WinDynamicDesktop

This would be really great to use the more recent versions.

**Comment by t1m0thyj** [comment]
The latest version on Winget is 4.7.0, the same as the latest version published everywhere else (GitHub, Microsoft Store, and Chocolatey).

Not sure what more recent versions you've seen? There are some recent changes in the develop branch (like multi-monitor support), which are not yet released because they are in alpha stage and still being tested.
