### ISSUE TITLE
UWP error

### ISSUE THREAD

**Issue by MisterGlasses** [t1m0thyj/WinDynamicDesktop#46]
执行的名称请求无效。此时无法检索请求的名称
![739e412153f975b3](https://user-images.githubusercontent.com/27768847/43067512-2ccd7428-8e2d-11e8-8860-45daa11e6ca8.png)

**Comment by MisterGlasses** [comment]
Don't  know what's wrong?

**Comment by t1m0thyj** [comment]
Sorry I don't know Chinese, but it seems the translation is "The executed name request is invalid. The requested name could not be retrieved at this time".

I haven't seen this error message before, so I'm not sure when it's happening. Did this message show up the first time you started the app, and prevent you from being able to run it? Or did it show up sometime later after the app was running for a while?

**Comment by MisterGlasses** [comment]
yes,your translations is right.it shown after I update my pc(07 update).Actually,other uwp app show the error too.And after I reboot my pc twice,It became normal.So when the error show next time,I'll feedback again.Thank you.

**Comment by t1m0thyj** [comment]
Since other UWP apps showed the same error and the problem went away after restarting, this sounds like it was caused by your PC and not the app. If you continue to experience issues with UWP apps, you could try the desktop version available [here](https://github.com/t1m0thyj/WinDynamicDesktop/releases). Feel free to open a new issue if you experience any other problems.
