### ISSUE TITLE
Toggle option to hide tray icon entry in taskbar

### ISSUE THREAD

**Issue by chrisquim** [t1m0thyj/WinDynamicDesktop#47]
Request for an enhancement feature to hide the tray icon in taskbar.
**Purpose:** To clean-up native system taskbar entries for users who opt to want it neat which also somehow makes the experience kinda native in the OS integration.
**Catch:** might cause question to unwary users on the app existence and background app persistence. Thus, the feature could be turn off by default and will prompt an information messagebox if enabled : (_i.e. that informs the user that the app will be running in the background without user interface. App can still be terminated at the task manager. And app toggles/options can be launch back again if the app is relaunch from the main .exe entry point application or thru registry entry toggle._) If feature is enabled, toggle should persist as "hidden UI" even if computer is restarted.

**Comment by chrisquim** [comment]
[https://github.com/t1m0thyj/WinDynamicDesktop/issues/28]
i was late to notice* that this matter has already been opened up in the previous issues. nevertheless it would be nice little touch if the feature could be toggled thru a user interface (perhaps a right click context menu entry) rather than going through manual setting config file editing.
(*sorry for opening 'it again' the topic as another issue.)

**Comment by t1m0thyj** [comment]
My original reasoning was that since you have to edit the config file manually to show the icon in the tray again, it seems consistent to require the same thing for hiding the icon. I see your point, but I'm also somewhat hesitant to add this to the user interface because the tray icon menu is already longer than most apps, and I don't want to clutter it with items.
