### ISSUE TITLE
Not starting on boot Windows 10

### ISSUE THREAD

**Issue by pliesenfeld** [t1m0thyj/WinDynamicDesktop#48]
Checked compatibility to run as admin in windows 10, no luck starting on boot, have to start manually.

**Comment by t1m0thyj** [comment]
Could you check the folder where the app EXE file is located and see if there is a file `WinDynamicDesktop.exe.log`? There should be if the program is crashing and failing to start, if so please post the contents here.

**Comment by t1m0thyj** [comment]
@pliesenfeld Unfortunately there isn't really a way to log more info, so I'm just trying to figure out as much as I can about the problem to hopefully be able to help.

I assume you're using the desktop version downloaded from GitHub, not the Microsoft Store app. It also sounds like you've downloaded the portable EXE, not the version with an installer. Did you select "Start on boot" in the installer, or from the system tray menu of the app?

Also when you say that you "see it in startup folder", do you mean in the registry? When you check "Start on boot" in WinDynamicDesktop, it should create a registry key but doesn't add anything to a startup folder on your disk.

**Comment by pliesenfeld** [comment]
Correct on question one: github

Startup folder, correct not in a "folder" but also I don't recall seeing it
in the registry editor (never looked), it's more in a service window that
includes startup items?  I think on task manager or something?  Not sure if
that's right.

**Comment by t1m0thyj** [comment]
Sorry for the delay in replying, unfortunately I'm not really sure what would be causing this.

One thought I did have, is did you happen to move the EXE file to a different location since first running the app? If you haven't already, try unchecking the "Start on boot" option in the app's system tray menu, then check it again and see if that makes a difference. That should reset the startup task.

Also just to be sure, the app is not running at all on boot? Have you clicked the arrow in your system tray to view all icons and the WinDynamicDesktop icon is not there? I assume that's the case, but want to make sure the app isn't starting up but somehow failing to change the wallpaper.

**Comment by pliesenfeld** [comment]
Thanks so much for your continued investigation!

I didn't move the .exe file, I did try unchecking and rechecking, no luck.
And I'm sure not running on boot -- It's weird because both my windows 10
machines are behaving the same way.. It really isn't a big deal, I've got
it pinned in my bottom bar now so I just click on it when I reboot, so no
biggie on my end.

Thanks!
Pete

**Comment by pliesenfeld** [comment]
2.0.1 fixed it!! Not sure what you did, but it loads on boot!! Woo hoo!!!
