### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by StormCoder7** [t1m0thyj/WinDynamicDesktop#51]
This is really just an aesthetic peeve but I was wondering if you could make the app in such a way that when you click the icon it launches a macOS themed tab with the toggle feature, rounded corners, buttons to maximise, minimise and close the app, etc. And I was also wondering if you can prevent the system from thinking that individual wallpapers are being used in the Setting apps, could you possibly add an icon of the app instead? I don't know anything about coding, so to be honest I don't know if you can do any of this. And could you add the Solar Gradient Dynamic Desktop wall paper as well? Thanks.

**Comment by t1m0thyj** [comment]
Thanks for the feedback, I've attempted to answer your questions below:
1. Not quite sure what you mean by "a macOS themed tab with the toggle feature, rounded corners, buttons to maximise, minimise and close the app, etc." Changing the user interface of the app to have a macOS theme would be difficult, and I don't have any plans to do that. However, I am hoping to release a new version of the app soon which will have a theme selector window somewhat similar to the wallpaper changer in macOS.
2. Regarding the Windows 10 Settings app thinking that all the wallpapers are separate, I've noticed that too and it is kind of annoying. I researched and found there are registry entries I could have my program edit so that it would only show a single wallpaper in the history of images displayed. I'm hesitant to do this because it would kind of be a registry hack, and although it would be nice not too important IMO.
3. The next version of the app will add the Solar Gradient wallpapers as an option, it's going to be a pretty big update actually.

**Comment by StormCoder7** [comment]
No worries,


What I meant by macOS themed tab was so you could just click the icon and make it open a full window rather than a list of options to give a really Mac like experience so it's basically a window that has that unique Mac style to it with the rounded buttons and stuff, so when you click the icon the window will look like the windows shown on: https://www.apple.com/au/macos/mojave-preview/

[https://www.apple.com/au/macos/mojave-preview/site/meta/og.png?201807171055]<https://www.apple.com/au/macos/mojave-preview/>

macOS - Mojave Preview - Apple (AU)<https://www.apple.com/au/macos/mojave-preview/>
www.apple.com
macOS Mojave. Dark Mode to put your work centre stage. New features to help you quickly organise and work on files. And the all-new Mac App Store.


and not like this: https://mk0intowindows84fvao.kinstacdn.com/wp-content/uploads/2015/05/Open-personalization-panel-Windows-10-method-2.png .


[https://mk0intowindows84fvao.kinstacdn.com/wp-content/uploads/2015/05/Open-personalization-panel-Windows-10-method-2.png]


I'll be honest, I know nothing about coding and have no idea if this is possible.


And you might want to consider adding a feature where you can get it to show the reverse of what's actually outside and another one where it's just dark. I think that if you do add the window thing it will look really cool if it also becomes dark.


And, BTW all my suggestions were meant to add aesthetics.


Hope you can add these features. Thanks. 😃

**Comment by t1m0thyj** [comment]
Just released version 2.0 which now has a theme manager. I believe this has improved the aesthetics of the app somewhat, although it looks like a standard Windows app which I think is the opposite of what you suggested unfortunately.

I'm open to aesthetic changes, but they generally aren't simple to do, so I don't really have time to implement a lot of them. Please try the new version and let me know if you have any different feedback based on it. Like do you think it would look better if the Theme Manager window had a dark background instead of light?

**Comment by DragoCubed** [comment]
I feel that the app should continue to be small. It would be nice to have a dark theme that can be enabled with or without the system wide toggle

**Comment by t1m0thyj** [comment]
I plan to continue keeping the app small, unfortunately there isn't a convenient way to theme WPF apps to be dark that looks good aesthetically. I also don't have enough time to add much to the app in the way of aesthetics right now. If anyone wants to improve the aesthetics, feel free to submit a PR.
