### ISSUE TITLE
Dark theme is not affecting explorer

### ISSUE THREAD

**Issue by maxsofar** [t1m0thyj/WinDynamicDesktop#53]
When **Dark Mode** is enabled it affects the **title** part of the **explorer** window, but not the **background**.
I'm currently using a RS5 preview build 17441, so maybe they changed the way dark theme is activated...

Anyway thanks for the app, you've done a great job 👍

**Comment by 19lmyers** [comment]
I'm using 19H1 (Skip Ahead 18219) right now, and the dark theme isn't toggling at all.

**Comment by t1m0thyj** [comment]
@maxsofar Thanks for the heads up, I don't think it makes sense for me to support preview versions of Windows. Hopefully this will resolve itself by the time Microsoft publishes the next major update of Windows 10.

@19lmyers Could you please try the new version 2.0.1? I think I may have fixed a bug causing this, but I'm not certain.

**Comment by 19lmyers** [comment]
Didn't fix the issue.

**Comment by t1m0thyj** [comment]
Theme changing seems broken now when I tested it in Win10 1809. Will look into this further and release an update if necessary when I have time.

**Comment by t1m0thyj** [comment]
After further testing in the latest version of Windows 10, it seems that changing the system theme (even from the Settings app) does not take effect in the File Explorer immediately. Unfortunately I am not aware of anything I can do to fix this in the app, the automatic theme change seems to be working otherwise.
