### ISSUE TITLE
Windows lock screen wallpapers can't update automatically. 

### ISSUE THREAD

**Issue by 1tonsilla** [t1m0thyj/WinDynamicDesktop#548]
- WDD Version:5.3.1
- OS Version:WIN10 enterprise LTSC 21h2(19044.3448)

Steps to Reproduce:
Lock screen wallpaper gets stuck and won't update. I've changed the new theme, and the wallpaper displayed on my desktop is correct, but the lock screen wallpaper is still the first WDD wallpaper to be set. I've restarted explorer but it doesn't work

Are you using the Microsoft Store version of WDD?:     
:No

**Comment by pettrichjonah** [comment]
Updated WDD to v5.5.0 and this feature doesn't work for me anymore. The option "Sync lock screen image with all displays" is active and I already restarted both WDD and my laptop.
I can select a separate image in the Windows settings but when I select WDD as the lock screen image, it always shows the same one. It's like WDD caches one theme and always sticks to it.

I am on Win11 23H2.

**Comment by t1m0thyj** [comment]
@pettrichjonah Could you enable debug logging by setting `"debugLogging": true` in `settings.json` and restarting WinDynamicDesktop? This will create a `debug.log` file where WinDD logs info every time it changes wallpaper on any display including the lockscreen.

After letting WinDD run for a few cycles where the wallpaper should have changed, please attach the `debug.log` file. This will help to determine whether there is a bug where WinDD doesn't try to update the lock screen image at all, or whether it's trying and the Windows API call is failing. I suspect it may be the latter since I've seen that happen before.

**Comment by pettrichjonah** [comment]
Thanks for the instructions - it now works for some reason. I can't really figure out why, but I think it was due to some messed up setting in Windows itself.

________________________________

**Comment by t1m0thyj** [comment]
@1tonsilla Do you experience this issue? If so, could you gather logs by following the steps in https://github.com/t1m0thyj/WinDynamicDesktop/issues/548#issuecomment-2119083815?

**Comment by cal4** [comment]
Working for me
