### ISSUE TITLE
The app cannot import themes if it uses certain language

### ISSUE THREAD

**Issue by febrimuhnas** [t1m0thyj/WinDynamicDesktop#580]
- WDD Version: 5.4.2
- OS Version: windows 11 pro 23h2

Hello. When I use the app in Javanese translation, I can't import the theme at all. I can only download themes available in the library on the left. Every time I try to import a theme (either by clicking the 'import from file' button or directly double-clicking the .ddw file), the import process gets stuck, and the progress bar doesn't move at all (like the image below). This problem occurs in all apps, both from GitHub and Windows Store.

![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/73753251/d2e89810-a18b-4750-a8d4-12c572f59565)

Surprisingly, when I tried using another language (eg: French), the theme import process occurred without a hitch.
![image](https://github.com/t1m0thyj/WinDynamicDesktop/assets/73753251/0b300dbd-0a29-4069-9f73-6a27418ecf92)

Please investigate this bug. Thank You.

**Comment by t1m0thyj** [comment]
This is due to some translations like Javanese having invalid format strings with placeholders like `{0}` or `{1}` missing.

I've added a script to detect invalid translation strings, and they should be fixed now. You can download a preview build here: https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/8577479010

**Comment by febrimuhnas** [comment]
It's works! Thankyou.
