### ISSUE TITLE
Change the system mode (light/dark) along with changing wallpapers

### ISSUE THREAD

**Issue by watchmakerful** [t1m0thyj/WinDynamicDesktop#617]
It would be great to implement automatic switching the Windows system mode (light/dark) together with wallpaper changes. Is this possible?

**Comment by t1m0thyj** [comment]
@watchmakerful To change the Windows system theme between light and dark, I recommend using [AutoDarkMode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode).

Using a separate app may not be ideal, but because Microsoft broke the easy way of programmatically changing system mode in Win11, it's not something trivial for me to implement and is better left to other apps.

If you don't want to have AutoDarkMode always running in the background, see [this comment](https://github.com/t1m0thyj/WinDynamicDesktop/issues/427#issuecomment-2439601279) for [a WinDD PowerShell script](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Installing-scripts) that will invoke AutoDarkMode when the wallpaper is changed.
