### ISSUE TITLE
[BUG] App in Win1809 don't change in dark mode/light mode

### ISSUE THREAD

**Issue by PaoloC95** [t1m0thyj/WinDynamicDesktop#68]
As a screenshot WinDynamicDesktop don't change perfectly the dark/light mode when change automatically.
![immagine](https://user-images.githubusercontent.com/43925971/46580267-e769c400-ca21-11e8-950c-00487a11dcee.png)

**Comment by DragoCubed** [comment]
Is this different to #53?

**Comment by t1m0thyj** [comment]
Unfortunately I can't do anything to fix this, Microsoft broke the automatic Windows 10 theme changing in version 1809 when they added the dark theme to File Explorer. If you change the theme between light and dark manually in the Windows 10 Settings app, you can observe the same behavior. The theme updates automatically in all of Windows except for in the File Explorer, because Microsoft implemented it poorly.

@DragoCubed You're right, this is basically the same issue.
