### ISSUE TITLE
Blurriness on Firewatch Theme

### ISSUE THREAD

**Issue by StormCoder7** [t1m0thyj/WinDynamicDesktop#85]
Um, something else about the Firewatch theme, is it just me or is the image really pixelated especially at the ridges at the bottom of the screen? I'm running my screen at 1366*768, not the best screen resolution but still, not what I expected coming from the high quality Mojave Desert theme. I don't know what you want from the log file, sorry. I'm running Windows 10 version 1809 and WinDynamicDesktop version 2.2.0.0 and I got WinDynamicDesktop from the Microsoft Store.

![highquality](https://user-images.githubusercontent.com/42315645/50547482-51df7880-0c8e-11e9-9490-f17a0976b64c.PNG)

**Comment by t1m0thyj** [comment]
The images in the Firewatch theme are 1080p, not quite as high resolution as the Mojave Desert theme but still I wouldn't expect them to look pixelated. Could you try this and let me know what happens?
* Find the folder where WinDynamicDesktop themes are installed (see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Finding-where-app-is-installed)).
* Navigate to the `themes/Firewatch` folder.
* Right click on `firewatch_8.jpg` and select "Set as desktop background".

If the image quality looks the same to you after doing that, then I'm not able to do anything to fix it. If it looks better than there is a problem with the app.

**Comment by StormCoder7** [comment]
Didn't do $#!T, have you got the same problem? Could you try replicating the issue?

**Comment by StormCoder7** [comment]
This is what's in the Notepad file,is there anything wrong?

{
  "imagesZipUri": "https://box.heliohost.org/Firewatch.zip",
  "imageFilename": "firewatch_*.jpg",
  "imageCredits": "Olly Moss",
  "dayImageList": [
    2,
    3,
    4,
    5,
    6
  ],
  "nightImageList": [
    7,
    8,
    1
  ]
}

**Comment by StormCoder7** [comment]
![notepad file](https://user-images.githubusercontent.com/42315645/50624105-c9ecbd80-0f70-11e9-916b-95150f476af3.PNG)

**Comment by t1m0thyj** [comment]
I did try replicating it, same issue for me when I set that image as a wallpaper from File Explorer. I agree the ridges at the bottom look pixelated in that image. The JSON file that you downloaded from GitHub is correct, the problem is the image file itself and I can't do anything about that unfortunately. 

Finding higher resolution versions of these images would be the only solution. Since this is a community created theme I don't know what URL the submitter got them from and can't really support the theme officially. I've googled for these images and can't find the exact same set, if you find higher res versions I'd be glad to update the Firewatch theme with them but I'm sorry I can't help more than that.
