### ISSUE TITLE
Want to help translate this program into Chinese

### ISSUE THREAD

**Issue by MSBelief** [t1m0thyj/WinDynamicDesktop#91]
Want to help translate this program into Chinese for many others who use it under Chinese. Also, Thank you for developing this wonderful application, like it so much!

**Comment by t1m0thyj** [comment]
Thanks for the interest in doing this. I don't have a framework for localization in the app right now, so don't have a way to add translations currently. I hope to add multi-language support to the app, will let you know when that happens and I'm ready for translations.

**Comment by t1m0thyj** [comment]
@MSBelief Just released version 3.1.0 which has experimental support for multiple languages. If you'd like to translate the app I'm planning to add the translation in the next version. Please follow these steps and let me know if you have any questions:
* Download the `messages.pot` file from [here](https://github.com/t1m0thyj/WinDynamicDesktop/blob/master/i18n/messages.pot)
* Download and install the free program [PoEdit](https://poedit.net/)
* Launch PoEdit and click the "Create new translation" button, then select the `messages.pot` file
* Go through the list of messages and translate each one
* Save your translation to a `.po` file (an `.mo` file will also automatically be generated)
* Copy the `.mo` file to the same folder as the app EXE (see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) if you don't know where that is)
* Close WinDynamicDesktop if it's running and edit the `settings.conf` file and change `language=null` to `language={LANGUAGE_NAME}` where `{LANGUAGE_NAME}` is the name of the `.mo` file (`{LANGUAGE_NAME}.mo`)
* Restart the app and you should see your translation
* Upload the `.po` file on GitHub so I can add the translation to the next version of the app

@FantasiaChan If you're still interesting in making a Russian translation that would be great too :)

**Comment by Tissitron** [comment]
Ok @t1m0thyj I just finished the French translation. Where can I upload the .po file on GitHub?
I've just create an account for the occasion so that why I'm a bit lost for now.
Thank you for your amazing work 🙂

**Comment by t1m0thyj** [comment]
@Tissitron GitHub doesn't seem to support uploading `.po` files, but you can rename it and change the extension to `.txt`. Then you can attach it here if you click "Attach files" at the bottom of the comment textbox.

**Comment by Tissitron** [comment]
So here it is @t1m0thyj !
Btw, even if I translated everything right, I noticed that some elements are still in english when I applied the `FR_fr.mo` file. Those elements do not seem to appear in the `messages.pot` file. So for future updates, could you please update it by adding the missing elements in it.
Anyway, you can count on me for the next French translations. 😉
[fr_FR.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2937578/fr_FR.txt)

**Comment by Harold-404** [comment]
@t1m0thyj First, Thank you for developing the great application, I like it very much and shared with my friends several times. I finished the Simplified Chinese translation, but when I edit the `settings.conf` file and restart the app, a error occurred like this image. I checked the `WinDynamicDesktop.exe.log` file but could't find the reason. 😥
Can you try this `zh_CN.mo` file again? I also want to translate to Traditional Chinese later. Anyway, thank you for giving me this chance that help more people use WinDynamicDesktop easily and comfortably.
[zh_CN.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2941440/zh_CN.txt)
![error](https://user-images.githubusercontent.com/33193357/53960691-e5677680-4121-11e9-8c00-2135218ea44e.png)
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/2941459/WinDynamicDesktop.exe.log)

**Comment by Tissitron** [comment]
> @t1m0thyj First, Thank you for developing the great application, I like it very much and shared with my friends several times. I finished the Simplified Chinese translation, but when I edit the `settings.conf` file and restart the app, a error occurred like this image. I checked the `WinDynamicDesktop.exe.log` file but could't find the reason. 😥
> Can you try this `zh_CN.mo` file again? I also want to translate to Traditional Chinese later. Anyway, thank you for giving me this chance that help more people use WinDynamicDesktop easily and comfortably.
> [zh_CN.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2941440/zh_CN.txt)
> ![error](https://user-images.githubusercontent.com/33193357/53960691-e5677680-4121-11e9-8c00-2135218ea44e.png)
> [WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/2941459/WinDynamicDesktop.exe.log)

Hi @Harold-404, when you edit the `settings.conf` you need to replace `"language":null` by `"language":"zh_CN"` in your case.

**Comment by Harold-404** [comment]
> > @t1m0thyj First, Thank you for developing the great application, I like it very much and shared with my friends several times. I finished the Simplified Chinese translation, but when I edit the `settings.conf` file and restart the app, a error occurred like this image. I checked the `WinDynamicDesktop.exe.log` file but could't find the reason. 😥
> > Can you try this `zh_CN.mo` file again? I also want to translate to Traditional Chinese later. Anyway, thank you for giving me this chance that help more people use WinDynamicDesktop easily and comfortably.
> > [zh_CN.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2941440/zh_CN.txt)
> > [WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/2941459/WinDynamicDesktop.exe.log)
> 
> Hi @Harold-404, when you edit the `settings.conf` you need to replace `"language":null` by `"language":"zh_CN"` in your case.
Wow! Thanks a lot! Seems I forgot to add `"` for `zh_CN` before. When I change `"language":zh_CN` to `"language":"zh_CN"`, it works! Here is a newer version of Chinese translation. Thank you again!
[zh_CN.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2942736/zh_CN.txt)

**Comment by MoritzBrueckner** [comment]
German translation: [de_DE.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2946643/de_DE.txt)


Unfortunately, some strings get cut off in the UI. ID's according to Poedit:
- **7**: If no solution is possible, "_Credits_" works in German too, everybody will understand it.
- **9**
- **47**: Could be changed to "_Importieren_" instead of "_Aus Datei importieren_" -> "_Import_" instead of "_Import from file_"

Also, the credits window is not wide enough to fully cover the text (ID **9**) below it.

Thank you for this great software :)

**Comment by FantasiaChan** [comment]
Russian translate is needed?

**Comment by FantasiaChan** [comment]
Russian Language is coming)

**Comment by sotiriszampras** [comment]
Here's the Greek language:)
[el_GR.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2979591/el_GR.txt)

**Comment by sotiriszampras** [comment]
Here's the Greek language:)
[el_GR.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/2979598/el_GR.txt)

**Comment by ceprickett** [comment]
You have been invited to the following event.

Title: (No Subject)
When: Wed Mar 27, 2019
Calendar:  
reply@reply.github.com
Who:
     * Christopher Prickett - organizer
     *  
reply@reply.github.com  
- optional

Your attendance is optional.

Event details:  
https://www.google.com/calendar/event?action=VIEW&eid=NGMxcm0xb2lvbmM4cWVrMWk5Y3QzNXVubDUgcmVwbHkrMDIzNTc4M2IxMjgxZjM1YjVhYjZkNTdhMzk3Yzg5ODIwZWNjZGNmYWZhYjY4MWRiOTJjZjAwMDAwMDAxMTg5ZjdkMDc5MmExNjljZTE3YmIxOWViQHJlcGx5LmdpdGh1Yi5jb20&tok=MjAjY2Vwcmlja2V0dEBnbWFpbC5jb21jYWJlMDRlZWZiOThmMmVkZGFhOGM5ODE1ZDZmNzViZjQ5NTA3M2Y3&ctz=America%2FNew_York&hl=en&es=0

Invitation from Google Calendar: https://www.google.com/calendar/

You are receiving this courtesy email at the account  
reply@reply.github.com  
because you are an attendee of this event.

To stop receiving future updates for this event, decline this event.  
Alternatively you can sign up for a Google account at  
https://www.google.com/calendar/ and control your notification settings for  
your entire calendar.

Forwarding this invitation could allow any recipient to modify your RSVP  
response. Learn more at  
https://support.google.com/calendar/answer/37135#forwarding

**Comment by t1m0thyj** [comment]
Thanks to all for the translations, I'm working on adding them to the next version of the app. In the meantime I've moved them to a separate repository and created issues for each of them: https://github.com/t1m0thyj/WDD-locale

@MoritzBrueckner The text getting cut off that you mentioned will also be fixed in the next version of the app, thanks for reporting it.

@Harold-404 It looks like you uploaded the `.mo` file instead of the `.po` file. Another user apparently didn't realize you had already made a Simplified Chinese translation and uploaded their `.mo` file. Could you upload your `.mo` file so that the translations can be compared?

**Comment by Harold-404** [comment]
> Thanks to all for the translations, I'm working on adding them to the next version of the app. In the meantime I've moved them to a separate repository and created issues for each of them: https://github.com/t1m0thyj/WDD-locale
> 
> @MoritzBrueckner The text getting cut off that you mentioned will also be fixed in the next version of the app, thanks for reporting it.
> 
> @Harold-404 It looks like you uploaded the `.mo` file instead of the `.po` file. Another user apparently didn't realize you had already made a Simplified Chinese translation and uploaded their `.mo` file. Could you upload your `.mo` file so that the translations can be compared?

Of course, Here are the `.po` file and `.mo` file for Simplified Chinese translation v3.1.0
[[v3.1.0]zh_CN.po.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/3052365/v3.1.0.zh_CN.po.txt)
[[v3.1.0]zh_CN.mo.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/3052366/v3.1.0.zh_CN.mo.txt)
Also I uploaded them to the issue of the separate repository `WDD-locale`: https://github.com/t1m0thyj/WDD-locale/issues/5#issuecomment-480658011. Should I submit the later translations for newer version to there separate repository `WDD-locale`  not here in the future?

**Comment by t1m0thyj** [comment]
Just released a new version (3.2.0) with the translations included.

@Harold-404 Yes, in the future please upload translations to the `WDD-locale` repository.

**Comment by PaoloC95** [comment]
[it_IT.txt](https://github.com/t1m0thyj/WinDynamicDesktop/files/3258427/it_IT.txt)

Italian Translation for WinDynamicDesktop.
