### ISSUE TITLE
WDD STILL not working in Win7

### ISSUE THREAD

**Issue by FantasiaChan** [t1m0thyj/WinDynamicDesktop#93]
![image](https://user-images.githubusercontent.com/39629381/51135809-f2679800-184b-11e9-8dee-c3949b128f25.png)

Log:
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в WinDynamicDesktop.ThemeManager.Initialize()
   в WinDynamicDesktop.AppContext..ctor() (Repeated about 20 times)
Windows 7
WDD version 2.3.0

P.s. I wrote here **2 months ago** and the bug is still not fixed (YandexTranslate)

**Comment by t1m0thyj** [comment]
The reason that issue was closed is because installing a newer version of NET Framework should fix this, it isn't a bug in the app AFAIK. Have you tried installing .NET 4.6.1 from here? https://www.microsoft.com/en-us/download/details.aspx?id=49981

**Comment by FantasiaChan** [comment]
Yes, I have a version .NET 4.7

**Comment by t1m0thyj** [comment]
Sorry for closing your issue prematurely before, I see now it wasn't the same as the one the other person had. Unfortunately it's pretty difficult for me to determine the cause of this bug and be able to fix it, because the error log isn't very helpful in this case to pinpoint the place in the code that caused it, since it doesn't mention an exact line number like it often does.

I know the problem isn't just Windows 7, because I know of users who are using the app fine on Windows 7. I'll look into this more when I get a chance.

**Comment by FantasiaChan** [comment]
I have experience with the log,I can help you make it better

**Comment by t1m0thyj** [comment]
Noticed that you closed the issue, did you find out what was causing it?

**Comment by FantasiaChan** [comment]
Nope

**Comment by FantasiaChan** [comment]
WDD 3.0.0 or new Windows fix the problem
