### ISSUE TITLE
win7 Errors occurred. 

### ISSUE THREAD

**Issue by superpyman** [t1m0thyj/WinDynamicDesktop#97]
After update the Verson 3.0.0, when start that will pop up "Errors occurred".
Win7 64bit;
WDD 3.0.0, the setup installation;
the screenshot:
![error](https://user-images.githubusercontent.com/22310538/51574803-5f34ff00-1eea-11e9-8aab-4988361a408b.png)

Logfile：
System.ArgumentNullException: 值不能为 null。
参数名: collection
   在 System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   在 WinDynamicDesktop.ThemeManager.FindMissingThemes()
   在 WinDynamicDesktop.ThemeManager.Initialize()
   在 WinDynamicDesktop.AppContext..ctor()
   在 WinDynamicDesktop.Program.Main()

**Comment by t1m0thyj** [comment]
Do you have any custom themes installed, or ones that you downloaded apart from the two bundled with the app? Based on the error message it seems like the problem is a theme that was made for an old version of the app. Theme JSON files are now required to include sections for "sunriseImageList" and "sunsetImageList", if this is missing in one of your theme files it could cause this error. If this is the case, it's still a bug in the app because even if the old theme files aren't compatible the error message should be more informative.

**Comment by superpyman** [comment]
Yes, I have installed some custom themes in the Verson 2.3.0. Now I uninstalled the old version completely and installed the new version, it seems OK now.
